### ISSUE TITLE
AWS токены в открытом доступе

### ISSUE THREAD

**Issue by subuk** [cazorla19/just-for-fun#1]
https://github.com/cazorla19/just-for-fun/commit/5339009d3cb7136a661867d00731501b9ad1d677#diff-cfc2a07e3ecd3d1d638561f27b46179b

Их нужно полностью убрать из истории репозитория и **обязательно** отозвать в AWS. Иначе в скором времени намайнишь биткойнов кому-нибудь за свой счет, если уже не успел.

**Comment by cazorla19** [comment]
Сделаю в течение суток.

**Comment by cazorla19** [comment]
Токены удалены из истории репозитория. Токены отозваны.
